/** Owner-authorized public résumé facts. Certification IDs, photographs and secrets are excluded. */
const skills = `AI / Agentic Engineering: OpenAI Agents SDK, LangChain, LangGraph, AutoGen, CrewAI, MCP server design and integration, RAG pipelines, Pinecone, Gemini Embeddings, agent evaluation frameworks, guardrails, prompt/agent design, and multi-provider orchestration (Groq/Llama 3.3, Gemini API, NVIDIA NIM).
Backend & Data: Python, FastAPI, Pydantic, DynamoDB, boto3, ReportLab, Google BigQuery.
Cloud & DevOps: AWS (EC2, S3, VPC, RDS, Elastic Beanstalk, ELB, EKS, Lambda, CloudWatch, SNS, CloudTrail, IAM), GCP, Azure, Docker, Kubernetes, Terraform, CloudFormation, Jenkins, Ansible, GitHub Actions, CI/CD.
Observability & Integration: Prometheus, Grafana, ELK Stack, Splunk, Cisco Tetration, Cisco Intersight, ServiceNow, Apache Kafka, AWS QuickSight, Power BI.
Frontend: Next.js, TypeScript, Vite, JavaScript, HTML, XML, GSAP, Three.js, Tailwind CSS.
Other skills: WordPress (custom themes, child themes, plugins, Elementor/WPBakery, SEO, caching, hosting, security and maintenance), Digital Marketing, Business Communication, client communication, ownership and cross-functional delivery. Digital Marketing and Business Communication were supplied directly by Ahmad; specific campaigns or results are not documented.`;

export const KNOWLEDGE = [
  { id: "profile", title: "Ahmad’s profile", href: "#identity", keywords: "ahmad hassan who about background developer engineer build builds overview location lahore pakistan", text: "Ahmad Hassan is an Agentic AI Developer and DevOps Engineer based in Lahore, Pakistan. His résumé states about six years of professional software/engineering experience, spanning web development, DevOps and agentic AI. His business-founder experience is a separate chapter. He builds tool-calling agents, multi-step reasoning systems, RAG pipelines, MCP integrations and evaluation/guardrail systems, supported by cloud and infrastructure experience. Projects include OpsPilot AI, InsightLoop, an AI Resume Builder and portfolio assistant, and the in-development CloudOps Knowledge Assistant." },
  { id: "skills", title: "Résumé · Skills", href: "#ahmad-ai", keywords: "skills skill technologies tech stack tools languages frameworks python fastapi pydantic dynamodb boto3 reportlab nextjs next typescript vite javascript html xml gsap three tailwind langchain langgraph autogen crewai openai pinecone embeddings groq gemini nvidia azure prometheus grafana elk splunk cisco servicenow kafka quicksight power bi", text: skills },
  { id: "experience", title: "Résumé · Experience", href: "#ahmad-ai", keywords: "experience years year long career history jobs job employment employers worked companies timeline professional resume cv", text: "Ahmad’s résumé states about six years of professional software/engineering experience; this is not six years exclusively in AI. Job history:\nAgentic AI Engineer — Algoustics Inc., May 2024–June 2026 (about two years).\nFounder & Operations — Sikandar Restaurant & BBQ, March 2022–March 2024 (business operations, separate from software engineering).\nDevOps Engineer — Onstak Inc., June 2019–March 2022 (nearly three years).\nWeb Developer — Ontrak Pvt Ltd, August 2018–May 2019.\nThese are the supplied résumé dates, not a claim of current employment. Current availability is not confirmed." },
  { id: "algoustics", title: "Résumé · Algoustics", href: "#ahmad-ai", keywords: "algoustics agentic engineer employment rag vector pinecone embeddings mcp evals guardrails", text: "Agentic AI Engineer at Algoustics Inc., May 2024–June 2026. Designed autonomous agents for multi-step reasoning, planning and task execution with LangChain, LangGraph, AutoGen and CrewAI; integrated tool/function calling with APIs, databases and services; developed RAG pipelines using Pinecone and Gemini Embeddings; designed and integrated MCP servers; built evaluation frameworks for accuracy, consistency and edge cases; implemented guardrails for safe agent behavior. No measured improvement percentage is supplied." },
  { id: "sikandar", title: "Résumé · Business ownership", href: "#ahmad-ai", keywords: "sikandar restaurant bbq founder business operations entrepreneurship owner management communication vendors staff customers", text: "Founder & Operations at Sikandar Restaurant & BBQ, March 2022–March 2024. Managed staff, customer service, suppliers and finances; established operational procedures; coordinated vendors, service providers and regulatory bodies; handled issue resolution, staff performance and daily decisions. This adds business ownership, client communication and delivery experience; it is not an additional software-engineering role." },
  { id: "onstak", title: "Résumé · Onstak", href: "#ahmad-ai", keywords: "onstak devops cloud infrastructure kubernetes eks terraform cloudformation jenkins ansible disaster recovery vpc telemetry", text: "DevOps Engineer at Onstak Inc., June 2019–March 2022. Provisioned production environments using CloudFormation/Terraform, including multi-VPC and disaster recovery environments; managed EKS clusters; automated builds/deployments with Jenkins and Ansible; administered EC2, S3, VPC, RDS, Elastic Beanstalk and ELB; contributed to GCP projects. Integrated Cisco Tetration with Kafka/Splunk, and Cisco Intersight with ServiceNow, WebEx and Microsoft Teams. Built AWS QuickSight and Power BI utilization dashboards." },
  { id: "ontrak", title: "Résumé · Ontrak", href: "#ahmad-ai", keywords: "ontrak web developer wordpress websites frontend themes plugins elementor wpbakery hosting seo caching security", text: "Web Developer at Ontrak Pvt Ltd, August 2018–May 2019. Created and maintained client/business websites across frontend and backend; designed interfaces/navigation; wrote and reviewed HTML, XML and JavaScript; integrated multimedia and tested/troubleshot applications with stakeholders. Built custom WordPress sites, theme customizations, child themes and plugins; configured Elementor/WPBakery, SEO and caching; managed hosting, security hardening and maintenance." },
  { id: "other-skills", title: "Ahmad · Additional skills", href: "#ahmad-ai", keywords: "wordpress digital marketing business communication soft skills client ownership cross functional seo themes plugins", text: "Ahmad also has WordPress, Digital Marketing and Business Communication skills. WordPress experience includes custom themes, child themes, plugins, Elementor/WPBakery, SEO/caching, hosting, security hardening and maintenance. Business ownership supports staff/vendor coordination, customer service, financial oversight, client communication and cross-functional delivery. No specific marketing campaign, ad-platform expertise or campaign metric was supplied." },
  { id: "education", title: "Résumé · Education", href: "#ahmad-ai", keywords: "education degree university superior bachelor bs software engineering study studied graduate graduation lahore", text: "BS Software Engineering, Superior University, Lahore, 2013–2017." },
  { id: "certifications", title: "Résumé · Certifications", href: "#ahmad-ai", keywords: "cert certs certification certifications certified certificate certificates aws practitioner associate google gcp cloud engineer", text: "Ahmad’s résumé lists AWS Cloud Practitioner (Amazon Web Services) and Associate Cloud Engineer (Google Cloud Platform). Issue dates, expiry/current validity and certification validation identifiers are not published." },
  { id: "infrastructure", title: "Infrastructure experience", href: "#infrastructure", keywords: "devops infrastructure terraform docker aws cloud deploy deployment ci cd provision security monitoring observability", text: "Ahmad’s cloud/DevOps skills include AWS, GCP, Azure, Docker, Kubernetes, Terraform, CloudFormation, Jenkins, Ansible, GitHub Actions, Prometheus, Grafana, ELK and Splunk. His Onstak role included production provisioning, multi-VPC/disaster recovery, EKS and CI/CD. OpsPilot source includes three Terraform-managed DynamoDB tables, a Dockerized FastAPI backend and GitHub Actions lint/test/build checks, with documented read-only IAM and request tracing. CloudOps’s larger AWS deployment remains planned; no measured uptime or savings is supplied." },
  { id: "agents", title: "Agent engineering", href: "#agentic-ai", keywords: "agent agentic ai reasoning tools mcp evaluation guardrails rag retrieval", text: "Ahmad builds planning/tool-calling agents, RAG, MCP integrations, evaluations and guardrails. Framework experience includes OpenAI Agents SDK, LangChain, LangGraph, AutoGen and CrewAI; provider orchestration includes Groq, Gemini and NVIDIA NIM. OpsPilot uses SDK-based orchestration and shared MCP services. InsightLoop has a hand-written plan/tool/observe loop with SQL retries and clarification. CloudOps is in development. No unmeasured evaluation score is available." },
  { id: "projects", title: "Ahmad · Project history", href: "#projects", keywords: "projects project portfolio built build shipped history achievements work", text: "Ahmad’s project history includes OpsPilot AI (AWS cost/idle-resource investigation), InsightLoop (agentic BigQuery analyst), AI-Powered Resume Builder (conversational résumé creation and PDF export), an earlier AI-powered portfolio assistant, and CloudOps Knowledge Assistant (RAG for cloud/DevOps, IN DEVELOPMENT). OpsPilot and InsightLoop have public repositories. CloudOps architecture/evaluation counts are planned and results remain unmeasured." },
  { id: "opspilot", title: "OpsPilot AI repository", href: "https://github.com/ahmad2474/opspilot-ai", keywords: "opspilot ops pilot aws finops cost idle resource investigation project", text: "OpsPilot AI is a read-only AWS cost/idle-resource investigation platform. It uses OpenAI Agents SDK, visible hypothesis/evidence/conclusion traces, and bounded fallback across Groq, Gemini and NVIDIA NIM. Ahmad’s résumé describes fixing an unbounded provider-hang bug through live debugging. A moto golden-account evaluation harness uses service-layer ground truth, not another LLM, to grade hallucination, tool correctness and injection resistance in CI. IAM enforces read-only access; a deletion-impact analyzer describes consequences without performing deletion. Shared services power agent, API and token-authenticated stdio JSON-RPC MCP, covering 15 resource types and 7 waste/FinOps categories. Stack: FastAPI, Python, Pydantic, boto3, OpenAI Agents SDK, MCP, DeepEval, moto, Next.js 14, TypeScript, NextAuth, Tailwind, DynamoDB, Terraform, AWS, GitHub Actions, Docker. No measured savings or adoption claim is supplied." },
  { id: "insightloop", title: "InsightLoop repository", href: "https://github.com/ahmad2474/insightloop", keywords: "insightloop insight loop sql bigquery analytics data analyst warehouse project", text: "InsightLoop is an agentic data analyst over a synthetic e-commerce BigQuery warehouse. Its hand-written framework-free agent loop plans, calls tools, observes and decides next steps, with SQL retries, compound-question decomposition and clarification. A live reasoning trace exposes planning/tool/self-correction steps. Gemini primary and Groq secondary share a tool schema/loop. BigQuery Sandbox and application SQL guards enforce read-only queries, block DDL/DML and apply row caps/timeouts. Stack: Next.js, TypeScript, Tailwind CSS, BigQuery, Gemini API, Groq/Llama 3.3, Vercel. No measured query accuracy is supplied." },
  { id: "resume-builder", title: "AI Resume Builder", href: "https://ai-resume-builder-tau-five.vercel.app", keywords: "resume builder cv pdf reportlab interview layouts conversational project", text: "AI-Powered Resume Builder: a Groq/Llama 3.3 conversational agent interviews users and generates résumé summaries, skills, experience and projects in real time. Ahmad’s résumé describes 5 selectable layouts and server-side PDF export. Stack includes Python, FastAPI, Next.js, Vite, JavaScript, Groq and ReportLab with Vercel deployment. Link supplied by Ahmad; no adoption or measured outcome is asserted." },
  { id: "earlier-portfolio", title: "Earlier portfolio assistant", href: "https://ahmad-hassan-portfolio-ten.vercel.app", keywords: "earlier previous portfolio assistant chatbot gemini website project", text: "Ahmad built an earlier portfolio end-to-end with AI-assisted development and an embedded Gemini-powered chatbot answering questions about his skills/past work. His supplied project stack includes Next.js, Vite, JavaScript, GSAP, Three.js and Vercel. This is an earlier portfolio, separate from the current Ahmad.AI implementation with Groq/Gemini fallback." },
  { id: "cloudops", title: "CloudOps planned scope", href: "#projects", keywords: "cloudops cloud ops knowledge assistant rag context bedrock opensearch titan bm25 cohere corpus development evaluation", text: "CloudOps Knowledge Assistant is IN DEVELOPMENT. Planned scope: FastAPI, OpenSearch, Amazon Bedrock, Next.js, Terraform; Titan V2 + BM25 hybrid retrieval, fusion, Cohere reranking, parent/child expansion, structure-aware incremental indexing, search-time role ACLs, citation validation, abstention, conflict detection, API logging/timeouts/retries/rate limiting/SSE/cost accounting, Review Bench, Terraform-managed AWS demo and teardown. Planned corpus/evaluation: 222 public documents, 115 synthetic internal documents including 70 incident post-mortems, 315 questions across 10 categories. Recall, faithfulness, authorization pass rates, latency, load, spend and deployment results are unmeasured. The $150 demo ceiling is a budget, not spend. Never describe planned features as shipped." },
  { id: "contact", title: "Contact Ahmad", href: "#contact", keywords: "contact email whatsapp linkedin github hire work together reach phone number links social connect", text: "Ahmad is based in Lahore, Pakistan. Email: ahmad_warraich@outlook.com. WhatsApp/phone: +92 302 6849341. GitHub: github.com/ahmad2474. LinkedIn: linkedin.com/in/ahmadhassan102. Current availability and rates are not confirmed; contact Ahmad directly. The assistant cannot send messages or contact anyone." },
  { id: "email", title: "Email Ahmad", href: "mailto:ahmad_warraich@outlook.com", keywords: "email mail", text: "Email Ahmad at ahmad_warraich@outlook.com." },
  { id: "whatsapp", title: "WhatsApp Ahmad", href: "https://wa.me/923026849341", keywords: "whatsapp phone number mobile", text: "Ahmad’s WhatsApp/phone number is +92 302 6849341." },
  { id: "github", title: "GitHub", href: "https://github.com/ahmad2474", keywords: "github repositories repo", text: "Ahmad’s GitHub is https://github.com/ahmad2474." },
  { id: "linkedin", title: "LinkedIn", href: "https://linkedin.com/in/ahmadhassan102", keywords: "linkedin social", text: "Ahmad’s LinkedIn is https://linkedin.com/in/ahmadhassan102." },
] as const;

export type KnowledgeId = typeof KNOWLEDGE[number]["id"];
export type AnswerSource = { id: string; title: string; href: string };
export type ProfileAnswer = { answer: string; sources: AnswerSource[]; mode: "profile" | "ai"; notice?: string };
export const OFF_TOPIC = "I’m Ahmad’s AI assistant, and I’m happy to help you learn about his skills, experience, projects or how to contact him. Your question seems to be outside that scope. What would you like to know about Ahmad?";
export const outOfScopeAnswer = (): ProfileAnswer => ({ mode: "profile", answer: OFF_TOPIC, sources: [] });
const followup = (q: string) => /^(tell me more|what else|and (then|there)|how long|what did he do there|which technologies)[?!.\s]*$/.test(q);

/** Fast deterministic boundaries; semantic scope is also checked in the model response. */
export function directAnswer(question: string): ProfileAnswer | null {
  const q = question.toLowerCase().trim();
  if (/^(hi|hello|hey|salam|assalam.?alaikum|thanks|thank you)[!.,\s]*$/.test(q)) return { mode: "profile", answer: "Hi! I’m Ahmad’s AI assistant. I can help with his skills, experience, projects, education or contact details. What would you like to know?", sources: [] };
  if (/\b(ignore (all |previous |your )?instructions|system prompt|api.?key|password|secret|pretend to be|act as|write (me )?(a |an )?(poem|essay|story)|weather|capital of|solve (this|the)|translate (this|the))\b/.test(q)) return outOfScopeAnswer();
  const related = /\b(ahmad|hassan|he|his|him|your|you|opspilot|insightloop|cloudops)\b/.test(q);
  const profileIntent = related || /\b(experience|skills?|technologies|languages|frameworks|tech stack|projects?|background|education|certs?|certifications?|contact|resume|cv|career|employment|jobs?|employers?|companies|algoustics|onstak|ontrak|sikandar|whatsapp|email|github|linkedin|ops pilot|insight loop|cloud ops)\b/.test(q);
  if (!profileIntent && !followup(q)) return outOfScopeAnswer();
  if (!related && /^(what (is|are)|explain|teach|how (do|can) i|write|generate|debug)\b/.test(q) && !/\b(experience|skills|projects|background|education|certifications|contact|resume|cv)\b/.test(q)) return outOfScopeAnswer();
  if (/\b(salary|age|birthday|married|wife|availability|available|street address|validation number|certification id|certification number|uptime|accuracy|recall|faithfulness|latency|savings|pass rate)\b/.test(q)) return { mode: "profile", answer: "I don’t have verified information for that specific detail. Ahmad’s availability and rates aren’t confirmed, and unmeasured project results aren’t published. You can ask him directly using the contact links below.", sources: KNOWLEDGE.filter(item => ["email", "whatsapp"].includes(item.id)).map(({ id, title, href }) => ({ id, title, href })) };
  return null;
}

export function profileAnswer(question: string, previousQuestion?: string): ProfileAnswer {
  const direct = directAnswer(question);
  if (direct) return direct;
  const query = (followup(question.toLowerCase().trim()) && previousQuestion ? previousQuestion + " " + question : question).toLowerCase();
  const sourceIds: KnowledgeId[] = [];
  if (/\b(location|city|country|based)\b|where.*\b(from|live|lives)\b/.test(query)) sourceIds.push("profile");
  if (/\b(skills|technologies|languages|frameworks|tech stack)\b/.test(query) && !/\b(opspilot|insightloop|cloudops|algoustics|onstak|ontrak|wordpress|marketing|communication)\b/.test(query)) sourceIds.push("skills");
  else if (/\b(projects|project history|all (his |your )?work)\b/.test(query)) sourceIds.push("projects");
  else if (/\b(years?|job history|career|employment|companies|employers|experience)\b/.test(query) && !/\b(algoustics|onstak|ontrak|sikandar|wordpress|marketing|communication|devops|agentic)\b/.test(query)) sourceIds.push("experience");
  else if (/\b(contact|reach|connect|social|links)\b/.test(query)) sourceIds.push("contact", "email", "whatsapp", "github", "linkedin");
  if (!sourceIds.length) {
    const words = (query.match(/[a-z0-9]+/g) ?? []).filter(word => !["about", "what", "does", "tell", "the", "and", "can", "his", "ahmad", "hassan", "you", "your", "have", "has", "did", "with", "for", "how", "where", "which", "that", "there", "more", "know", "used", "use"].includes(word));
    const ranked = KNOWLEDGE.map(item => {
      const body = new Set(item.text.toLowerCase().match(/[a-z0-9]+/g));
      const score = words.filter(word => word.length > 2).reduce((sum, word) => sum + (item.keywords.split(" ").includes(word) ? 2 : body.has(word) ? 1 : 0), 0);
      return { item, score: score + (query.replaceAll(" ", "").includes(item.id.replaceAll("-", "")) ? 8 : 0) };
    }).sort((a, b) => b.score - a.score);
    const best = ranked[0];
    if (!best.score) return /\b(ahmad|hassan|he|his|him|you|your)\b/.test(query) ? { mode: "profile", answer: "I don’t have that detail in Ahmad’s supplied profile. I can help with his documented skills, job history, projects, education and contact details, or you can ask him directly.", sources: [{ id: "contact", title: "Contact Ahmad", href: "#contact" }] } : outOfScopeAnswer();
    sourceIds.push(best.item.id);
  }
  const selected = sourceIds.map(id => KNOWLEDGE.find(item => item.id === id)!);
  return { mode: "profile", answer: selected[0].text, sources: selected.map(({ id, title, href }) => ({ id, title, href })) };
}
