/** Public, curated facts. Never ingest raw photographs, private CV IDs or secrets. */
export const KNOWLEDGE = [
  { id: "profile", title: "Ahmad’s profile", href: "#identity", keywords: "ahmad hassan who about background experience skills stack developer engineer", text: "Ahmad Hassan is an Agentic AI Developer and DevOps Engineer. His work connects tool-using agents, evidence-backed answers and infrastructure. His public projects include OpsPilot AI, InsightLoop, and the in-development CloudOps Knowledge Assistant. He works with Python, TypeScript, FastAPI, Next.js, AWS, Terraform, Docker, CI/CD, agent orchestration, MCP and retrieval systems. No verified years-of-experience count, employer history, availability or salary is included in this public knowledge base." },
  { id: "infrastructure", title: "Infrastructure evidence", href: "https://github.com/ahmad2474/opspilot-ai/blob/main/.github/workflows/ci.yml", keywords: "devops infrastructure terraform docker aws cloud deploy deployment ci cd provision security monitoring observability", text: "OpsPilot’s source includes a Terraform module for three DynamoDB tables, a Docker build for its FastAPI backend, and GitHub Actions workflows for backend lint/tests/image builds and frontend lint/builds. Its documentation describes read-only IAM, request-ID tracing and an audit log. These are project artifacts; they do not establish enterprise production usage or measured uptime. CloudOps’s larger Terraform/AWS deployment is planned, not completed." },
  { id: "agents", title: "Agent engineering", href: "#agentic-ai", keywords: "agent agentic ai reasoning tools mcp evaluation guardrails rag retrieval", text: "Ahmad’s projects emphasize planning, explicit tool calls, read-only boundaries, visible execution traces and evaluation. OpsPilot uses the OpenAI Agents SDK and shared services exposed through MCP. InsightLoop has a hand-written plan/tool/observe loop with SQL retries and clarification. CloudOps is being developed around hybrid retrieval, search-time authorization and evidence-grounded generation. No unmeasured evaluation score is available." },
  { id: "opspilot", title: "OpsPilot AI repository", href: "https://github.com/ahmad2474/opspilot-ai", keywords: "opspilot ops pilot aws finops cost idle resource investigation project", text: "OpsPilot AI is a read-only AWS investigation and cost/idle-resource analysis project. Its repository documents 15 resource types, visible tool traces, shared Python services for the API/agent/MCP, provider fallback, investigation recall and a moto-based evaluation harness. It cannot create, modify or delete AWS resources. Its Terraform module provisions DynamoDB tables, not a complete AWS platform. Repository documentation/source were reviewed; live operation, production adoption and measured savings were not independently verified." },
  { id: "insightloop", title: "InsightLoop repository", href: "https://github.com/ahmad2474/insightloop", keywords: "insightloop insight loop sql bigquery analytics data analyst warehouse project", text: "InsightLoop is an agentic data analyst over a synthetic e-commerce BigQuery warehouse. Its source has a custom agent loop, get_schema/run_sql/ask_clarifying_question tools, retry handling and visible traces. The query client validates single SELECT/WITH statements, blocks disallowed keywords, injects a row cap and uses a timeout. Its documentation describes Gemini with Groq fallback. No measured query accuracy or production usage is asserted." },
  { id: "cloudops", title: "CloudOps planned scope", href: "#projects", keywords: "cloudops cloud ops knowledge assistant rag context bedrock opensearch titan bm25 cohere corpus development evaluation", text: "CloudOps Knowledge Assistant is IN DEVELOPMENT. Ahmad supplied its intended end-product scope: FastAPI, OpenSearch, Amazon Bedrock, Next.js and Terraform; Titan V2 dense retrieval plus BM25, fusion, Cohere reranking, parent/child expansion, search-time role ACLs, citation validation, abstention, conflict handling, API observability and a Review Bench. Planned scope: 222 public documents, 115 synthetic internal documents including 70 incident post-mortems, and 315 evaluation questions across 10 categories. Recall, faithfulness, authorization pass rates, latency, load, cost and deployment results remain unmeasured. These planned features must never be described as already shipped." },
  { id: "contact", title: "Contact Ahmad", href: "#contact", keywords: "contact email whatsapp linkedin github hire work together reach phone", text: "Ahmad’s public contact details: email ahmad_warraich@outlook.com; WhatsApp +923026849341 (https://wa.me/923026849341); GitHub https://github.com/ahmad2474; LinkedIn https://linkedin.com/in/ahmadhassan102. Current job availability and rates are not verified; ask Ahmad directly. The assistant cannot contact anyone or send messages." },
] as const;

export type KnowledgeId = typeof KNOWLEDGE[number]["id"];
export type AnswerSource = { id: string; title: string; href: string };
export type ProfileAnswer = { answer: string; sources: AnswerSource[]; mode: "profile" | "ai"; notice?: string };

export function profileAnswer(question: string): ProfileAnswer {
  const query = question.toLowerCase();
  const unsupported = /\b(salary|age|birthday|address|married|wife|password|secret|api key|availability|available|years|uptime|accuracy|recall|faithfulness|latency|savings)\b/.test(query);
  if (unsupported) return { mode: "profile", answer: "I don’t have verified information for that. CloudOps’s performance and cost results are still pending. For personal details, availability or rates, please ask Ahmad directly.", sources: [{ id: "contact", title: "Contact Ahmad", href: "#contact" }] };
  const words = (query.match(/[a-z0-9]+/g) ?? []).filter(word => !["about", "what", "does", "tell", "the", "and", "can", "his"].includes(word));
  const ranked = KNOWLEDGE.map(item => ({ item, score: words.filter(word => word.length > 2 && item.keywords.split(" ").includes(word)).length + (["opspilot", "insightloop", "cloudops"].includes(item.id) && query.replaceAll(" ", "").includes(item.id) ? 5 : 0) })).sort((a, b) => b.score - a.score);
  const best = ranked[0];
  if (!best.score) return { mode: "profile", answer: "I can help with Ahmad’s engineering skills, OpsPilot AI, InsightLoop, CloudOps’s planned design, or ways to contact him. I don’t have verified information about that question.", sources: [] };
  return { mode: "profile", answer: best.item.text, sources: [{ id: best.item.id, title: best.item.title, href: best.item.href }] };
}
