const OPSPILOT_SOURCE = "https://github.com/ahmad2474/opspilot-ai/blob/b2157a713f33755d1bfdf14effcd1bc54d23ddf8";
const INSIGHTLOOP_SOURCE = "https://github.com/ahmad2474/insightloop/blob/e41c45d6f5537da1946edfd2c6974451887ddf8d";
const CLOUDOPS_SOURCE = "https://github.com/ahmad2474/cloudops-rag/blob/5447ad26a6f26915b5cfd508c72d735e7b41d20a";

export const PROJECTS = [
  {
    slug: "opspilot-ai",
    key: "opspilot",
    name: "OpsPilot AI",
    number: "01",
    category: "AWS / AGENTIC OPERATIONS",
    status: "SOURCE AVAILABLE",
    headline: "Investigate the cloud. Keep the evidence.",
    summary: "A read-only AWS resource and cost investigation workspace. A Next.js galaxy view, FastAPI routes, an OpenAI Agents SDK investigator and token-gated MCP tools all draw from the same service layer.",
    stack: ["Next.js", "FastAPI", "boto3", "OpenAI Agents SDK", "DynamoDB", "MCP"],
    delivery: "Terraform documents an AWS EC2 path; live deployment is unverified.",
    evidence: ["Collectors for 15 AWS resource types and seven waste checks", "Moto fixtures and a service-layer oracle for deterministic evaluation", "Read-only deletion-impact analysis that does not delete resources"],
    repository: "https://github.com/ahmad2474/opspilot-ai",
    visual: "RESOURCE INVESTIGATION / SHARED SERVICES",
    problemHeading: "Cloud costs need context.",
    problem: "An AWS cost question spans inventory, idle signals, prices and dependencies. OpsPilot brings those observations into one investigation while making the agent's tool calls and findings inspectable.",
    flow: [
      ["Inspect", "The Next.js galaxy and chat surface selected account resources and the investigation trace."],
      ["Orchestrate", "FastAPI passes a chat turn to an OpenAI Agents SDK runner with bounded provider fallback."],
      ["Use shared tools", "Thin agent and MCP tools call the same scan, waste, cost and impact services as API routes."],
      ["Read AWS", "Services call boto3 through a read-only client; concurrent collectors isolate failures and reuse cached scans."],
      ["Retain evidence", "Tool results return to the trace, while investigations can be embedded and stored in DynamoDB for recall."],
    ],
    architecture: [
      ["One source of cloud logic", "API routes, agent tools and token-gated MCP tools share services rather than maintaining separate AWS calculations."],
      ["Analysis without mutation", "The deletion-impact path inspects EC2, RDS and EBS relationships. It does not terminate resources."],
      ["Deterministic checks", "A moto-backed golden account lets the evaluation harness compare answers and traces with service-derived facts."],
    ],
    sources: [
      ["System map and boundaries", `${OPSPILOT_SOURCE}/README.md`],
      ["Agent orchestration", `${OPSPILOT_SOURCE}/opspilot-backend/app/agent/orchestrator.py`],
      ["Concurrent resource scan", `${OPSPILOT_SOURCE}/opspilot-backend/app/services/scan_service.py`],
      ["Read-only impact analysis", `${OPSPILOT_SOURCE}/opspilot-backend/app/services/deletion_impact_service.py`],
      ["MCP service interface", `${OPSPILOT_SOURCE}/opspilot-backend/app/mcp/server.py`],
      ["Evaluation oracle", `${OPSPILOT_SOURCE}/opspilot-backend/eval/oracle/build_oracle.py`],
    ],
    boundary: "The public source supports these components and evaluation methods. This review did not run a live AWS account, verify savings or confirm production adoption. The documented single-admin and static IAM-key model is not presented as a multi-tenant production security design.",
  },
  {
    slug: "insightloop",
    key: "insightloop",
    name: "InsightLoop",
    number: "02",
    category: "DATA / AGENTIC ANALYTICS",
    status: "SOURCE AVAILABLE",
    headline: "A question. A query. A trace you can follow.",
    summary: "A Next.js data agent explores a synthetic retail warehouse in BigQuery. A hand-written loop chooses tools, guards read-only SQL, retries bounded failures and streams its investigation trace to the interface.",
    stack: ["Next.js", "TypeScript", "BigQuery", "Gemini", "Groq"],
    delivery: "Next.js server route and BigQuery Sandbox design; live deployment is unverified.",
    evidence: ["Custom loop bounded to nine tool rounds and three SQL retries", "Only a single SELECT or WITH query passes the SQL guard", "Streamed steps and a final answer over NDJSON"],
    repository: "https://github.com/ahmad2474/insightloop",
    visual: "QUERY / OBSERVE / CLARIFY",
    problemHeading: "A result needs a trail.",
    problem: "A data question may need schema discovery, a query, error recovery or a clarification. InsightLoop exposes that process instead of showing a final answer with no path back to the underlying data.",
    flow: [
      ["Ask", "The Next.js chat route accepts a question and opens an NDJSON response stream."],
      ["Plan", "The custom loop sends the current state to a Gemini or Groq adapter with a common tool schema."],
      ["Choose a tool", "The agent can inspect schema, run SQL or ask a clarifying question."],
      ["Constrain BigQuery", "The SQL client permits one read-only SELECT/WITH statement, caps returned rows and cancels timed-out jobs."],
      ["Observe", "Results or errors feed the next bounded step, while the UI shows trace events, SQL and the final answer."],
    ],
    architecture: [
      ["Explicit loop", "The application owns the plan, tool, observe and retry cycle rather than hiding it inside a framework."],
      ["Query boundary", "The BigQuery client rejects mutating statements and applies a 15-second timeout with job cancellation."],
      ["Visible reasoning", "Step and completion events drive the trace panel, so the user can inspect the query path."],
    ],
    sources: [
      ["System overview", `${INSIGHTLOOP_SOURCE}/README.md`],
      ["Agent loop", `${INSIGHTLOOP_SOURCE}/src/lib/agent/loop.ts`],
      ["Tool contracts", `${INSIGHTLOOP_SOURCE}/src/lib/agent/tools.ts`],
      ["BigQuery query guard", `${INSIGHTLOOP_SOURCE}/src/lib/bigquery/client.ts`],
      ["Streamed API response", `${INSIGHTLOOP_SOURCE}/src/app/api/chat/route.ts`],
      ["Retail schema", `${INSIGHTLOOP_SOURCE}/src/lib/bigquery/schema.ts`],
    ],
    boundary: "The public source supports the loop, guards and UI trace. This review did not independently run BigQuery, establish answer accuracy or verify production usage and business outcomes.",
  },
  {
    slug: "cloudops-knowledge-assistant",
    key: "cloudops",
    name: "CloudOps Knowledge Assistant",
    number: "03",
    category: "CONTEXT / OPERATIONS INTELLIGENCE",
    status: "IN DEVELOPMENT",
    headline: "Operations knowledge. With an evidence trail.",
    summary: "An in-development RAG system for on-call cloud and DevOps questions. Its repository contains ingestion, hybrid retrieval, search-time role filters, grounded-answer checks, a FastAPI service and a Review Bench interface. Live provider evaluation and the AWS demo remain pending.",
    stack: ["FastAPI", "OpenSearch", "Amazon Bedrock", "Next.js", "Terraform"],
    delivery: "Terraform defines VPC, EC2, managed OpenSearch, ECR, IAM and CloudWatch; apply is pending.",
    evidence: ["Manifest: 222 documents total, including 115 synthetic internal documents and 70 incident files", "Evaluation dataset: 315 questions across 10 categories; measured scores are pending", "API, retrieval, security and Review Bench code are present; Terraform is authored but not applied"],
    repository: "https://github.com/ahmad2474/cloudops-rag",
    visual: "RETRIEVE / AUTHORIZE / GROUND / REVIEW",
    problemHeading: "Evidence must respect access.",
    problem: "On-call engineers need answers that respect access rights, cite the right evidence and abstain when sources are insufficient. This system is being built around those constraints, with retrieval and answer checks that can be inspected.",
    flow: [
      ["Ingest", "Structure-aware chunks and parent sections are indexed with content hashes for incremental updates."],
      ["Authorize", "Role filters enter both vector and BM25 OpenSearch queries before retrieved text reaches the model."],
      ["Retrieve", "Titan V2 embeddings and BM25 results can be fused by RRF or weighted scoring, then reranked and expanded to parent context."],
      ["Ground", "Generation code checks citations, source conflicts and evidence strength, then abstains when support is insufficient."],
      ["Review", "FastAPI returns sources and a retrieval trail; the Next.js Review Bench presents answer, evidence and evaluation surfaces."],
    ],
    architecture: [
      ["Search-time access", "ACLs are applied inside each search query and preserved through context expansion, before LLM input."],
      ["Inspect the answer", "Citation validation and abstention are built into the answer path; streamed clients receive a final validated response."],
      ["Evaluate before claiming", "The 315-question dataset and harness exist, but baseline scores and live Bedrock comparisons have not been published."],
    ],
    sources: [
      ["Status and phase record", `${CLOUDOPS_SOURCE}/README.md`],
      ["Corpus manifest", `${CLOUDOPS_SOURCE}/data/manifest.json`],
      ["Retrieval pipeline", `${CLOUDOPS_SOURCE}/docs/retrieval.md`],
      ["Security model", `${CLOUDOPS_SOURCE}/docs/security.md`],
      ["API contract", `${CLOUDOPS_SOURCE}/docs/api.md`],
      ["Evaluation dataset", `${CLOUDOPS_SOURCE}/data/evaluation/dataset.json`],
      ["AWS Terraform design", `${CLOUDOPS_SOURCE}/infrastructure/terraform/main.tf`],
    ],
    boundary: "Code and local test paths are present, but real Bedrock and OpenSearch evaluation, Terraform apply, AWS spend and load-test results are pending. No retrieval score, faithfulness, latency, security pass rate or production deployment is claimed.",
  },
] as const;

export type PortfolioProject = (typeof PROJECTS)[number];

export function getProject(slug: string) {
  return PROJECTS.find(project => project.slug === slug);
}
